/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Find the PID of the process listening on the given port.
 * Searches TCP (LISTEN state) and UDP on both IPv4 and IPv6.
 * Returns null if not found.
 */
export declare function findPidByPort(port: number): number | null

/**
 * Kill a process by PID.
 * - force=true:  SIGKILL (Unix) / TerminateProcess (Windows) — immediate
 * - force=false: SIGTERM (Unix) / taskkill /PID (Windows) — graceful
 * Returns true if the signal was sent successfully.
 */
export declare function kill(pid: number, force?: boolean): boolean

/**
 * Find the process on `port` and kill it.
 * Returns the killed PID, or null if no process was found.
 */
export declare function killByPort(port: number, force?: boolean): number | null
